name: Benchmarks (mini suite)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run mini benchmark suite
        run: |
          python -m zeroproof.bench --suite all --out benchmark_results --iterations 300 --samples 3
          python -m zeroproof.overhead_cli --out benchmark_results/overhead.json
      - name: Upload benchmark artifact
        uses: actions/upload-artifact@v4
        with:
          name: mini-benchmarks
          if-no-files-found: ignore
          path: |
            benchmark_results/*.json
            benchmark_results/summary.txt
