name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (pinned to pre-commit versions)
        run: |
          python -m pip install --upgrade pip
          pip install \
            black==23.7.0 \
            ruff==0.4.0 \
            isort==5.12.0 \
            mypy==1.4.1

      - name: Run Black
        run: black --check --diff zeroproof

      - name: Run Ruff
        run: ruff check zeroproof

      - name: Run isort
        run: isort --check-only --diff zeroproof

      - name: Run MyPy (public surface)
        run: mypy
